<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="0" finished="true" name="Test Run: 2" tests="3" total_time="Finished in: 0.00 secs."/>
<test location="C:\Users\Mark_Kwong\Dropbox\LHS Shared New\PythonWorkspace\Basic Test Case\basictests.py" status="ok" test="BasicTests.testOne" time="0.00">
<stdout/>
<stderr/>
</test>
<test location="C:\Users\Mark_Kwong\Dropbox\LHS Shared New\PythonWorkspace\Basic Test Case\basictests.py" status="error" test="BasicTests.testThree" time="">
<stdout/>
<stderr><![CDATA[Traceback (most recent call last):
  File "C:\Users\Mark_Kwong\Dropbox\LHS Shared New\PythonWorkspace\Basic Test Case\basictests.py", line 23, in testThree
    self.b.printSquare(3)
AttributeError: 'Basic' object has no attribute 'printSquare'
]]></stderr>
</test>
<test location="C:\Users\Mark_Kwong\Dropbox\LHS Shared New\PythonWorkspace\Basic Test Case\basictests.py" status="ok" test="BasicTests.testTwo" time="0.00">
<stdout/>
<stderr/>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="Basic Test Case basictests.py"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
